DISEASE_CATALOG = [
    {
        "key": "tomato_bacterial_spot",
        "name": "Bacterial Spot",
        "sample_image": "/assets/diseases/bacterial_spot.jpg",
        "symptoms": "Muncul bercak kecil gelap pada daun, kadang dikelilingi halo kuning.",
        "cause": "Bakteri Xanthomonas spp. pada kondisi lembap dan percikan air.",
        "handling": "Gunakan benih sehat, kurangi percikan air, sanitasi kebun, dan rotasi tanaman.",
    },
    {
        "key": "tomato_early_blight",
        "name": "Early Blight",
        "sample_image": "/assets/diseases/early_blight.jpg",
        "symptoms": "Bercak cokelat dengan pola cincin konsentris, biasanya dari daun bawah.",
        "cause": "Jamur Alternaria solani, dipicu kelembapan dan stres tanaman.",
        "handling": "Pangkas daun terinfeksi, tingkatkan sirkulasi udara, dan gunakan fungisida sesuai dosis.",
    },
    {
        "key": "tomato_late_blight",
        "name": "Late Blight",
        "sample_image": "/assets/diseases/late_blight.jpg",
        "symptoms": "Lesi basah kehitaman yang cepat meluas, daun dapat layu mendadak.",
        "cause": "Patogen Phytophthora infestans yang berkembang pada cuaca sejuk-lembap.",
        "handling": "Segera isolasi tanaman sakit, kurangi kelembapan, dan lakukan kontrol fungisida preventif.",
    },
    {
        "key": "tomato_leaf_mold",
        "name": "Leaf Mold",
        "sample_image": "/assets/diseases/leaf_mold.jpg",
        "symptoms": "Bercak kuning pada permukaan atas daun dan beludru kehijauan/cokelat di bawah daun.",
        "cause": "Jamur Fulvia fulva pada greenhouse atau area lembap dengan ventilasi buruk.",
        "handling": "Perbaiki ventilasi, hindari kelembapan tinggi berkepanjangan, dan buang daun terinfeksi.",
    },
    {
        "key": "tomato_septoria_leaf_spot",
        "name": "Septoria Leaf Spot",
        "sample_image": "/assets/diseases/septoria_leaf_spot.jpg",
        "symptoms": "Bercak kecil abu-abu dengan tepi gelap, banyak muncul pada daun tua.",
        "cause": "Jamur Septoria lycopersici dan penyebaran melalui air hujan/irigasi.",
        "handling": "Buang sisa tanaman sakit, lakukan mulsa, dan aplikasikan fungisida jika diperlukan.",
    },
    {
        "key": "tomato_spider_mites",
        "name": "Spider Mites",
        "sample_image": "/assets/diseases/spider_mites.jpg",
        "symptoms": "Daun menguning berbintik halus, terdapat jaring tipis di bawah daun.",
        "cause": "Serangan tungau laba-laba pada kondisi panas dan kering.",
        "handling": "Semprot air pada bawah daun, gunakan musuh alami, atau akarisida sesuai anjuran.",
    },
    {
        "key": "tomato_target_spot",
        "name": "Target Spot",
        "sample_image": "/assets/diseases/target_spot.jpg",
        "symptoms": "Bercak melingkar besar dengan pola target, daun dapat mengering.",
        "cause": "Jamur Corynespora cassiicola pada area lembap dan padat tanaman.",
        "handling": "Kurangi kepadatan tanam, sanitasi rutin, dan kontrol fungisida terjadwal.",
    },
    {
        "key": "tomato_yellow_leaf_curl_virus",
        "name": "Tomato Yellow Leaf Curl Virus",
        "sample_image": "/assets/diseases/yellow_leaf_curl_virus.jpg",
        "symptoms": "Daun mengeriting ke atas, menguning, tanaman kerdil, dan buah berkurang.",
        "cause": "Virus TYLCV yang ditularkan lalat putih (whitefly).",
        "handling": "Kendalikan vektor whitefly, gunakan varietas toleran, dan cabut tanaman terinfeksi berat.",
    },
    {
        "key": "tomato_mosaic_virus",
        "name": "Tomato Mosaic Virus",
        "sample_image": "/assets/diseases/mosaic_virus.jpg",
        "symptoms": "Pola mosaik hijau muda-gelap pada daun, daun keriting, pertumbuhan terhambat.",
        "cause": "Virus ToMV melalui kontak mekanis, alat, atau benih terkontaminasi.",
        "handling": "Sterilisasi alat, hindari kontak silang, dan gunakan benih/bibit bersertifikat sehat.",
    },
    {
        "key": "tomato_healthy",
        "name": "Healthy",
        "sample_image": "/assets/diseases/healthy.jpg",
        "symptoms": "Daun hijau merata tanpa bercak/nekrosis yang signifikan.",
        "cause": "Tidak terdeteksi indikasi penyakit pada citra daun.",
        "handling": "Lanjutkan perawatan rutin: irigasi stabil, nutrisi seimbang, dan monitoring berkala.",
    },
]
